apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: rabbitmq-system
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
  - name: rabbitmq-tcp
    port: 5672
    targetPort: 5672
    protocol: TCP
    nodePort: 31000
  - name: rabbitmq-web
    port: 15672
    targetPort: 15672
    protocol: TCP
    nodePort: 32000