apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray
  labels:
    app: v2ray
spec:
  replicas: 1
  template:
    metadata:
      name: v2ray
      labels:
        app: v2ray
    spec:
      containers:
        - name: v2ray-server
          image: v2fly/v2fly-core
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10086
          volumeMounts:
            - name: server-config
              mountPath: /etc/v2ray
      volumes:
        - name: server-config
          configMap:
            name: v2ray-config
            items:
              - key: v2ray-server
                path: config.json
      restartPolicy: Always
  selector:
    matchLabels:
      app: v2ray
