apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
      - pods/log
      - services
      - services/status
      - endpoints
      - endpoints/status
      - deployments
    verbs:
      - get
      - list
      - watch