---
- name: download cfssl
  get_url:
    url: '{{ etcd.download_url }}/{{ etcd.version }}/etcd-{{ etcd.version }}-linux-amd64.tar.gz'
    dest: '{{ etcd.temp_dir }}'
    validate_certs: no
    timeout: 20
  register: etcd_download
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"
  environment: '{{ proxy.system }}'
  when: not etcd_archive.stat.exists