apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dts
  name: debezium-mysql8
  labels:
    app: debezium-mysql8
spec:
  selector:
    matchLabels:
      app: debezium-mysql8
  replicas: 1
  template:
    metadata:
      name: debezium-mysql8
      labels:
        app: debezium-mysql8
    spec:
      containers:
        - name: debezium-mysql8
          image: mysql:8.0.27
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
          ports:
            - containerPort: 3306
              name: mysql
      restartPolicy: Always
