apiVersion: v1
kind: Service
metadata:
  name: mysql-57-keyring
spec:
  selector:
    app: mysql-57-keyring
  ports:
    - port: 3306
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-57-keyring
  labels:
    app: mysql-57-keyring
spec:
  replicas: 1
  template:
    metadata:
      name: mysql-57-keyring
      labels:
        app: mysql-57-keyring
    spec:
      containers:
        - name: mysql
          image: d1zbnocg.mirror.aliyuncs.com/library/mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: config-volume
              mountPath: /etc/mysql/mysql.conf.d
      restartPolicy: Always
      volumes:
#         - name: mysql-persistent-storage
#           persistentVolumeClaim:
#             claimName:  mysql-pv-claim
        - name: config-volume
          configMap:
            name: mysql-57-keyring-config
            items:
                - key: server-config
                  path: my.cnf
  selector:
    matchLabels:
      app: mysql-57-keyring

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-57-keyring-config
data:
  server-config: |
    [mysqld]
    server_id = 1
    early-plugin-load=keyring_file.so

    # binlog
    gtid_mode=on                 #开启gtid模式
    enforce_gtid_consistency=on  #强制gtid一致性，开启后对于特定create table不被支持
    log-bin=mysql-bin
    log-slave-updates=1

