apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: default
spec:
  selector:
    app: my-nginx
  type: NodePort
  ports:
  - name: my-nginx
    port: 30080
    targetPort: 80
    protocol: TCP
    nodePort: 30080