apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: default
spec:
  selector:
    app: test-nginx
  type: NodePort
  ports:
  - port: 30080
    targetPort: 80
    protocol: TCP
    nodePort: 30080