apiVersion: apps/v1
kind: Deployment
metadata:
  name:  test-nginx
  namespace: default
  labels:
    app:  test-nginx
spec:
  selector:
    matchLabels:
      app: test-nginx
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  test-nginx
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  test-nginx
        image:  nginx
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: nginx-conf
          configMap:
            name: test-nginx
      restartPolicy: Always